 spring:
   application:
     name: Config-Default
  eureka:
    instance:
     prefer-ip-address: true
    fetch-registry: true
     register-with-eureka: true
       defaultZone: http://localhost:8761/eureka
